# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libXTrap

# >> macros
# << macros

Summary:    X.Org X11 libXTrap runtime library
Version:    1.0.1
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org/
Source0:    ftp://ftp.x.org/pub/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXTrap.yaml
Patch0:     libxtrap-pcfix.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xorg-macros) >= 1.17
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xt)
BuildRequires:  pkgconfig(trapproto)

%description
%{summary}.


%package devel
Summary:    Development components for the libXTrap library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.



%prep
%setup -q -n %{name}-%{version}

# libxtrap-pcfix.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_libdir}/libXTrap.so.6
%{_libdir}/libXTrap.so.6.4.0
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc AUTHORS README ChangeLog
%{_libdir}/libXTrap.so
%{_libdir}/pkgconfig/xtrap.pc
# << files devel
